### ISSUE TITLE
Wrong library name in Windows build in kea-config.bat

### ISSUE THREAD

**Issue by gillins** [ubarsc/kealib#18]
See https://github.com/conda-forge/kealib-feedstock/issues/43

For some reason the output name on Windows is `libkea.lib` (not sure this is intentional). We should ensure that the contents of `kea-config.bat` match (currently outputs `kea.lib`).

**Comment by zklaus** [comment]
Thanks, @gillins, for taking this up. I am fairly certain that in principle the library file should be called `kea.lib`, *not* `libkea.lib`.

**Comment by gillins** [comment]
I think there might have been an attempt to keep the naming similar to Unix for some reason, I can't remember. Anyway I don't think we can change it now without breaking everything...
I'm a bit mystified as to _how_ is gets named `libkea.lib` but when I have a moment I'll have a look under Windows.
