### ISSUE TITLE
kea file in xarray? 

### ISSUE THREAD

**Issue by juan-guerschman** [ubarsc/kealib#25]
Hi there,

I am trying to open a kea file in xarray.
both `xr.open_dataset(fname, engine="rasterio")` and `rioxarray.open_rasterio(fname)` work and return a DataSet or a DataArray but none of them return the attribute table anywhere. 

Anaconda install in Windows, I have kealib 1.4.14 installed. 

Any ideas what I could do? 

Thanks

**Comment by gillins** [comment]
Neither `xarray` nor `rioxarray` appear to support raster attribute tables... I would recommend using the gdal Python bindings to access the RAT like this:
```
ds = gdal.Open(fname)
band = ds.GetRasterBand(1)
rat = band.GetDefaultRAT()
numCols = rat.GetColumnCount()
data = rat.ReadAsArray(0)
```
If you are after a higher level abstraction I recommend [RIOS](https://www.rioshome.org/en/latest/) and in particular the [rios.ratapplier](https://www.rioshome.org/en/latest/rios_ratapplier.html) and [rios.rat](https://www.rioshome.org/en/latest/rios_rat.html) modules.

**Comment by gillins** [comment]
Hi @juan-guerschman I'm closing this. I assume you got what you needed? Feel free to ping me on a Cibolabs call if you want.
