### ISSUE TITLE
kealib and osgeo4w

### ISSUE THREAD

**Issue by odgersn** [ubarsc/kealib#29]
Novice question so please bear with me.

I'm on Windows and have installed kealib v. 1.4.14-1 and hdf5 v. 1.10.7-8 via osgeo4w. I can see that the osgeo4w installer has installed `libkea.dll` into `OSGeo4W/bin/`. But when I run `gdalinfo --formats` from the osgeo4w shell, I can't see the `KEA` format in the list. Is there something else I need to do to allow osgeo4w GDAL to recognise libkea?

**Comment by gillins** [comment]
Unfortunately I don't know much about osgeo4w, so we might have to try some things. Has the installer created a `gdal_KEA.dll` file anywhere? This is the library that makes KEA available to GDAL and is needed in addition to `libkea.dll`. If not, see if there is an option to install it. 
If that doesn't fix it you might need to check that your [GDAL_DRIVER_PATH](https://trac.osgeo.org/gdal/wiki/ConfigOptions#GDAL_DRIVER_PATH) environment variable is set to the directory with `gdal_KEA.dll` in it... (I would have thought the installer would do this for you).
Just pinging @bhjolly in case he knows more.

**Comment by odgersn** [comment]
Aha! Yes I can see that `gdal_KEA.dll` is a separate plugin for the osgeo4w ecosystem. Will update my installation and see how we go.

**Comment by odgersn** [comment]
Installing the `gdal_KEA.dll` plugin from the osgeo4w installer works. :)
