### ISSUE TITLE
Properly define DllExport and use another name

### ISSUE THREAD

**Issue by SpaceIm** [ubarsc/kealib#7]
I'm creating a recipe of `KEALib` for https://github.com/conan-io/conan-center-index, in order to add this option in `GDAL` recipe.

Currently, `DllExport` is defined like this in `KEACommon.h`

```c++
#ifndef DllExport
    #ifdef _MSC_VER
        #define DllExport   __declspec( dllexport )
    #else
        #define DllExport
    #endif
#endif
```

Therefore, `KEALib`:
- does not allow to properly hide symbols with others compilers than Visual Studio if shared.
- always define `DllExport` as  `__declspec( dllexport )` at build time with Visual Studio while it shouldn't if static.
- does not define `DllExport` as `__declspec(dllimport)` for consumers if shared and Visual Studio.

Moreover, `DllExport` name is way too common for a macro defined in a public header. You should prefer something like `KEALIB_EXPORT` or `KEALIB_API`

Since `KEALib` already relies on CMake 3.5, you could use `GenerateExportHeader` (https://cmake.org/cmake/help/v3.5/module/GenerateExportHeader.html) to have a consistent macro (based on compiler, static/shared, and proper definition injected at build time so that consumers don't need to care about this) in a generated header file `export_libkea.h` to include in `KEACommon.h`.

Here for example what this generated header file would look like:

if shared and Visual Studio:

```c++
#ifndef LIBKEA_API_H
#define LIBKEA_API_H

#ifdef LIBKEA_STATIC_DEFINE
#  define LIBKEA_API
#else
#  ifndef LIBKEA_API
#    ifdef libkea_EXPORTS
        /* We are building this library */
#      define LIBKEA_API __declspec(dllexport)
#    else
        /* We are using this library */
#      define LIBKEA_API __declspec(dllimport)
#    endif
#  endif
#endif

#endif /* LIBKEA_API_H */
```

if shared and GNU compilers:

```c++
#ifndef LIBKEA_API_H
#define LIBKEA_API_H

#ifdef LIBKEA_STATIC_DEFINE
#  define LIBKEA_API
#else
#  ifndef LIBKEA_API
#    ifdef libkea_EXPORTS
        /* We are building this library */
#      define LIBKEA_API __attribute__((visibility ("default")))
#    else
        /* We are using this library */
#      define LIBKEA_API
#    endif
#  endif
#endif

#endif /* LIBKEA_API_H */
```

if static:

```c++
#ifndef LIBKEA_API_H
#define LIBKEA_API_H

#ifdef LIBKEA_STATIC_DEFINE
#  define LIBKEA_API
#else
#  ifndef LIBKEA_API
#    ifdef libkea_EXPORTS
        /* We are building this library */
#      define LIBKEA_API
#    else
        /* We are using this library */
#      define LIBKEA_API
#    endif
#  endif
#endif

#endif /* LIBKEA_API_H */
```

With this, you can also add `set_property(TARGET ${LIBKEA_LIB_NAME} PROPERTY CXX_VISIBILITY_PRESET hidden)` in `src/CMakeLists.txt`

**Comment by gillins** [comment]
Thanks for this. Would you mind submitting a PR with these changes?

Note that HDF5 doesn't build statically in multithreaded mode on Windows so I haven't done much testing with static builds as a result.

**Comment by SpaceIm** [comment]
@gillins I'll see what I can do.

**Comment by gillins** [comment]
@SpaceIm Can you review these changes: https://github.com/ubarsc/kealib/compare/exportheader and let me know what you think? I found it harder than expected to get it working....
