### ISSUE TITLE
simple kea file manipulation in python?

### ISSUE THREAD

**Issue by juan-guerschman** [ubarsc/kealib#70]
hey @gillins a basic question about using kea files.

My use case needs to 
1- subset a very large kea file 
2- read the RAT into a pandas DF  (this is under control) https://github.com/ubarsc/kealib/issues/25 
3- do stuff with the data
4- write new attribute(s) to the rat 
5- visualise the results, ideally in QGis 

I am stuck already on 1 - trying to use a simple gdal.warp and not working, not sure why. 
And I think I'll need a nudge with 4. 
Is 5 even possible? I remember you pointing me to the tui viewer tool which I never used in the end.
I have been doing all this converting all to a geodatabase, but the memory overheads are huge.

**Comment by gillins** [comment]
1. Have you tried gdal_translate with the -srcwin or -projwin options? How large is the area? If it is too much for memory you can restrict the area the RIOS function is applied to with https://www.rioshome.org/en/latest/rios_applier.html#rios.applier.ApplierControls.setFootprintType - I can give some assistance there.
2-4. I'd strongly urge you to use RIOS's ratapplier (https://www.rioshome.org/en/latest/rios_ratapplier.html) so you don't need to read all the data into memory at once. You can also do manipulation there and create new columns
5. Indeed tuiview - this was designed mainly for doing stuff with RAT's - Qgis not so good. I know you had some trouble installing that (which turned out to be a conda problem in the end) but this is all fixed now I think. Happy to give you a hand if you need.

Anyway, above are the tools I've been involved with so a little bit biased. But - I know them very well and can support them.

**Comment by juan-guerschman** [comment]
> 1. Have you tried gdal_translate with the -srcwin or -projwin options? How large is the area? If it is too much for memory you can restrict the area the RIOS function is applied to with https://www.rioshome.org/en/latest/rios_applier.html#rios.applier.ApplierControls.setFootprintType - I can give some assistance there.

I actually wanted to use a geojson polygon for the subset, that's why I was trying gdal.Warp with the cutlineDSName option. What pisses me off is that I don't get an error message, but there is no output produced, don't know where the problem is.

>    2-4. I'd strongly urge you to use RIOS's ratapplier (https://www.rioshome.org/en/latest/rios_ratapplier.html) so you don't need to read all the data into memory at once. You can also do manipulation there and create new columns

ok, will go to rios. 

> 2. Indeed tuiview - this was designed mainly for doing stuff with RAT's - Qgis not so good. I know you had some trouble installing that (which turned out to be a conda problem in the end) but this is all fixed now I think. Happy to give you a hand if you need.

thanks

**Comment by gillins** [comment]
If you are using vectors, I should point out that you can read the vector in RIOS (https://www.rioshome.org/en/latest/applierexamples.html#vector-inputs) and mask your data with it...

If you need to do per segment stats, then pyshepseg has got a bunch of functions for doing this in a memory efficient manner. See: https://www.pyshepseg.org/en/latest/#per-segment-statistics

Also pinging @neilflood as he has a wealth of experience with doing this stuff.

**Comment by juan-guerschman** [comment]
ok, you are opening even more questions. 

Can I do my kea subsettimg (using a vector file) directly in rios? I have done something similar with a "normal" tif file before, but not sure if it will work with a kea. And if it does, will the RAT be updated? I mean, deleting all the elements that were in the original kea but are not there anymore in the cropped kea file. 

And in terms of using a vector to mask (and subset):  will it work? I have some code that I adapted from @tonykgill that first rasterizes the vector to the same grid, and then uses the raster. He says he needed that because he used the `controls.setFootprintType(applier.BOUNDS_FROM_REFERENCE)` option, not available for a vector. Is that right?

**Comment by gillins** [comment]
So, is your vector a square or an irregular shape?

If it is a square and you just want a subset with an updated RAT for that subset see this function:  https://www.pyshepseg.org/en/latest/pyshepseg_subset.html#pyshepseg.subset.subsetImage

If it is irregular it is a bit more complex. Yes I think you are right about BOUNDS_FROM_REFERENCE not working with vector. But would you actually want to subset? Are you accumulating values (where vector == 1), or do you want to write an image? You might have to tell us a bit more about what you are trying to do....

**Comment by gillins** [comment]
I've just remembers that `subsetImage` takes a `maskImage`. So if you have an irregular shape we have got you covered too. Just need to ratserize that vector to the same grid as the input image...

**Comment by juan-guerschman** [comment]
it is irregular (a group of farms)
I have a very large kea (all of Aus, 25 meter pixel).  It's the output from pyshepseg, something that Peter produced. 
I want to use only the segments (pixels) within this group of farms, read some of the attributes in the RAT, run a clustering algorithm and save the output(s) as a new element(s) in the RAT.

**Comment by gillins** [comment]
OK I think subsetImage is what you want then. Can you rasterize your farms to be on the same grid as your large kea? Something like this should work:
```
gdal_rasterize -of KEA -tr 25 25 -tap -burn 1 -init -0 farms.geojson farm_mask.kea
```
Then get the size of this output (pass this in as newXsize and newYsize). Unfortunately, subsetImage does not (yet) use the georeferencing information in the mask file so you'll have to work out tlx and tly yourself. Something like this should work:
```
large_ds = gdal.Open('largenationalraster.kea')
large_transform = large_ds.GetGeoTransform()
large_inv = gdal.InvGeoTransform(large_transform)

small_ds = gdal.Open('farm_mask.kea')
small_transform = small_ds.GetGeoTransform()
tlx, tlx = gdal.ApplyGeoTransform(large_inv, small_transform[0], small_transform[3])
newXsize = small_ds.RasterXSize
newYsize = small_ds.RasterYSize
```
(see https://gdal.org/en/latest/user/raster_data_model.html#affine-geotransform)

**Comment by neilflood** [comment]
Hi @juan-guerschman 

Firstly, most things which work with other formats also work with KEA, so no problem there. 

Second - are you writing a new output KEA, for just the extent of the farms vector? Or are you trying to modify certain rows of the large KEA file, just for the pixels contained in the farm. That would be quite tricky and potentially problematic, depending on exactly what you are doing. 

If you are wanting a new, small KEA, just for the farms area, with new RAT data, then do as @gillins is saying - first subset the KEA (with its RAT columns) into a small one, and then use RIOS's ratapplier to do some calculations on the RAT, writing new columns back into the small KEA.

**Comment by juan-guerschman** [comment]
> Second - are you writing a new output KEA, for just the extent of the farms vector? Or are you trying to modify certain rows of the large KEA file, just for the pixels contained in the farm. That would be quite tricky and potentially problematic, depending on exactly what you are doing.
> 
> If you are wanting a new, small KEA, just for the farms area, with new RAT data, then do as @gillins is saying - first subset the KEA (with its RAT columns) into a small one, and then use RIOS's ratapplier to do some calculations on the RAT, writing new columns back into the small KEA.

awesome thanks. Yes, I don't want to mess with the large KEA, that's why I wanted to subset first. I'll try what @gillins suggested. Thanks both!

**Comment by juan-guerschman** [comment]
> I've just remembers that `subsetImage` takes a `maskImage`. So if you have an irregular shape we have got you covered too. Just need to ratserize that vector to the same grid as the input image...

sorry @gillins . Where is `subsetImage`?

**Comment by juan-guerschman** [comment]
this?
https://www.pyshepseg.org/en/latest/pyshepseg_subset.html#pyshepseg.subset.subsetImage

**Comment by neilflood** [comment]
> this? https://www.pyshepseg.org/en/latest/pyshepseg_subset.html#pyshepseg.subset.subsetImage

That's it.

**Comment by gillins** [comment]
Yes, you'll have to have `pyshepseg` installed to access it.

**Comment by neilflood** [comment]
There is also a command line wrapper, which installs with pyshepseg, called `pyshepseg_subset`, which may be good enough.

**Comment by juan-guerschman** [comment]
subsetImage is failing, with errors related to the gdal creation options: 
```
outname = 'C:/Users/Juan/OneDrive - Cibo Labs Pty Ltd/scratch/AACo/LRUs/test.kea'
outformat= 'KEA'

#creationOptions=['INTERLEAVE=PIXEL','COMPRESS=DEFLATE','TILED=YES','BIGTIFF=YES','NUM_THREADS=ALL_CPUS','BLOCKXSIZE=64','BLOCKYSIZE=64','PREDICTOR=2','ZLEVEL=9'] 

subsetImage(image, outname, tlx, tly, newXsize, newYsize, outformat, creationOptions=creationOptions, origSegIdColName=None, maskImage=None)
```
the error:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[4], line 10
      5 creationOptions=['COMPRESS=DEFLATE', 'ZLEVEL=9', 'TILED=NO', 'INTERLEAVE=PIXEL']
      6 #creationOptions=['COMPRESS=DEFLATE']
      7 #creationOptions=[]
      8 #creationOptions=None
---> 10 subsetImage(image, outname, tlx, tly, newXsize, newYsize, outformat, creationOptions=creationOptions, origSegIdColName=None, maskImage=None)
     11 #subsetImage(image, outname, tlx, tly, newXsize, newYsize, outformat, origSegIdColName=None, maskImage=None)

File ~\anaconda3\envs\seg\lib\site-packages\pyshepseg\subset.py:88, in subsetImage(inname, outname, tlx, tly, newXsize, newYsize, outformat, creationOptions, origSegIdColName, maskImage)
     85     raise PyShepSegSubsetError(msg)
     87 driver = gdal.GetDriverByName(outformat)
---> 88 outds = driver.Create(outname, newXsize, newYsize, 1, inband.DataType,
     89             options=creationOptions)
     90 # set the output projection and transform
     91 outds.SetProjection(inds.GetProjection())

File ~\anaconda3\envs\seg\lib\site-packages\osgeo\gdal.py:2273, in Driver.Create(self, *args, **kwargs)
   2271 def Create(self, *args, **kwargs) -> "GDALDatasetShadow *":
   2272     r"""Create(Driver self, char const * utf8_path, int xsize, int ysize, int bands=1, GDALDataType eType=GDT_Byte, char ** options=None) -> Dataset"""
-> 2273     return _gdal.Driver_Create(self, *args, **kwargs)

RuntimeError: Attempt to create file `C:/Users/Juan/OneDrive - Cibo Labs Pty Ltd/scratch/AACo/LRUs/test.kea' failed. Invalid creation option(s)
```
the same error comes up with the following alternatives:
```
#creationOptions=['INTERLEAVE=PIXEL','COMPRESS=DEFLATE','TILED=YES','BIGTIFF=YES','NUM_THREADS=ALL_CPUS','BLOCKXSIZE=64','BLOCKYSIZE=64','PREDICTOR=2','ZLEVEL=9'] 
creationOptions=['COMPRESS=DEFLATE', 'ZLEVEL=9', 'TILED=NO', 'INTERLEAVE=PIXEL']
#creationOptions=['COMPRESS=DEFLATE']
```
and if I pass `creationOptions=None``: 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[5], line 10
      6 #creationOptions=['COMPRESS=DEFLATE']
      7 #creationOptions=[]
      8 creationOptions=None
---> 10 subsetImage(image, outname, tlx, tly, newXsize, newYsize, outformat, creationOptions=creationOptions, origSegIdColName=None, maskImage=None)

File ~\anaconda3\envs\seg\lib\site-packages\pyshepseg\subset.py:88, in subsetImage(inname, outname, tlx, tly, newXsize, newYsize, outformat, creationOptions, origSegIdColName, maskImage)
     85     raise PyShepSegSubsetError(msg)
     87 driver = gdal.GetDriverByName(outformat)
---> 88 outds = driver.Create(outname, newXsize, newYsize, 1, inband.DataType,
     89             options=creationOptions)
     90 # set the output projection and transform
     91 outds.SetProjection(inds.GetProjection())

File ~\anaconda3\envs\seg\lib\site-packages\osgeo\gdal.py:2273, in Driver.Create(self, *args, **kwargs)
   2271 def Create(self, *args, **kwargs) -> "GDALDatasetShadow *":
   2272     r"""Create(Driver self, char const * utf8_path, int xsize, int ysize, int bands=1, GDALDataType eType=GDT_Byte, char ** options=None) -> Dataset"""
-> 2273     return _gdal.Driver_Create(self, *args, **kwargs)

TypeError: not a sequence
```

any ideas?

**Comment by neilflood** [comment]
The creation options are specific to the output format. KEA format has only some very technical creation options, and usually the best choice is an empty list (i.e. []).

**Comment by juan-guerschman** [comment]
an empty list also throws an error: 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[6], line 10
      7 creationOptions=[]
      8 #creationOptions=None
---> 10 subsetImage(image, outname, tlx, tly, newXsize, newYsize, outformat, creationOptions=creationOptions, origSegIdColName=None, maskImage=None)

File ~\anaconda3\envs\seg\lib\site-packages\pyshepseg\subset.py:137, in subsetImage(inname, outname, tlx, tly, newXsize, newYsize, outformat, creationOptions, origSegIdColName, maskImage)
    134 ysize = min(tileSize, newYsize - topLine + tly)
    136 # extract the image data for this tile from the input file
--> 137 inData = inband.ReadAsArray(leftPix, topLine, xsize, ysize)
    139 # work out the range of data for accessing the whole RAT (below)
    140 inDataMasked = inData[inData != shepseg.SEGNULLVAL]

File ~\anaconda3\envs\seg\lib\site-packages\osgeo\gdal.py:4150, in Band.ReadAsArray(self, xoff, yoff, win_xsize, win_ysize, buf_xsize, buf_ysize, buf_type, buf_obj, resample_alg, callback, callback_data)
   4145 """ Reading a chunk of a GDAL band into a numpy array. The optional (buf_xsize,buf_ysize,buf_type)
   4146 parameters should generally not be specified if buf_obj is specified. The array is returned"""
   4148 from osgeo import gdal_array
-> 4150 return gdal_array.BandReadAsArray(self, xoff, yoff,
   4151                                    win_xsize, win_ysize,
   4152                                    buf_xsize, buf_ysize, buf_type, buf_obj,
   4153                                    resample_alg=resample_alg,
   4154                                    callback=callback,
   4155                                    callback_data=callback_data)

File ~\anaconda3\envs\seg\lib\site-packages\osgeo\gdal_array.py:428, in BandReadAsArray(band, xoff, yoff, win_xsize, win_ysize, buf_xsize, buf_ysize, buf_type, buf_obj, resample_alg, callback, callback_data)
    426     if buf_type == gdalconst.GDT_Byte and band.GetMetadataItem('PIXELTYPE', 'IMAGE_STRUCTURE') == 'SIGNEDBYTE':
    427         typecode = numpy.int8
--> 428     buf_obj = numpy.empty([buf_ysize, buf_xsize], dtype=typecode)
    430 else:
    431     if len(buf_obj.shape) not in (2, 3):

TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by juan-guerschman** [comment]
btw if useful:
```
pyshepseg.__version__, gdal.__version__
'2.0.2', '3.6.3'
```

**Comment by gillins** [comment]
Sorry, should have said that tlx, tly, newXsize, newYsize all need to be integers (I think they come out of ApplyGeoTransform as floats).

**Comment by neilflood** [comment]
This is a separate problem. What is the type of the parameters tlx, tly, newXsize, newYsize? These should all be integers. If any of them are floats, you would get some error like this one.

**Comment by juan-guerschman** [comment]
thanks!
new error 
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[21], line 10
      4 #creationOptions=['INTERLEAVE=PIXEL','COMPRESS=DEFLATE','TILED=YES','BIGTIFF=YES','NUM_THREADS=ALL_CPUS','BLOCKXSIZE=64','BLOCKYSIZE=64','PREDICTOR=2','ZLEVEL=9'] 
      5 #creationOptions=['COMPRESS=DEFLATE', 'ZLEVEL=9', 'TILED=NO', 'INTERLEAVE=PIXEL']
      6 #creationOptions=['COMPRESS=DEFLATE']
      7 #creationOptions=None
      9 creationOptions=[]
---> 10 subsetImage(image, outname, tlx, tly, newXsize, newYsize, outformat, creationOptions=creationOptions, origSegIdColName=None, maskImage=None)

File ~\anaconda3\envs\seg\lib\site-packages\pyshepseg\subset.py:88, in subsetImage(inname, outname, tlx, tly, newXsize, newYsize, outformat, creationOptions, origSegIdColName, maskImage)
     85     raise PyShepSegSubsetError(msg)
     87 driver = gdal.GetDriverByName(outformat)
---> 88 outds = driver.Create(outname, newXsize, newYsize, 1, inband.DataType,
     89             options=creationOptions)
     90 # set the output projection and transform
     91 outds.SetProjection(inds.GetProjection())

File ~\anaconda3\envs\seg\lib\site-packages\osgeo\gdal.py:2273, in Driver.Create(self, *args, **kwargs)
   2271 def Create(self, *args, **kwargs) -> "GDALDatasetShadow *":
   2272     r"""Create(Driver self, char const * utf8_path, int xsize, int ysize, int bands=1, GDALDataType eType=GDT_Byte, char ** options=None) -> Dataset"""
-> 2273     return _gdal.Driver_Create(self, *args, **kwargs)

RuntimeError: 
```

**Comment by neilflood** [comment]
What are the values of newXsize and newYsize?

**Comment by juan-guerschman** [comment]
```
image = 'C:/Users/Juan/Cibo Labs Pty Ltd/CiboSharepointArchive - CiboSharepointArchive/Data/raster/LandResponse/aus_100_5.kea'
mask = "C:/Users/Juan/OneDrive - Cibo Labs Pty Ltd/data/vector/aaco/AACo_stations_rangelands_buff5km.tif"

large_ds = gdal.Open(image)
large_transform = large_ds.GetGeoTransform()
large_inv = gdal.InvGeoTransform(large_transform)

small_ds = gdal.Open(mask)
small_transform = small_ds.GetGeoTransform()
tlx, tly = gdal.ApplyGeoTransform(large_inv, small_transform[0], small_transform[3])
tlx = int(tlx)
tly = int(tly)

newXsize = small_ds.RasterXSize
newYsize = small_ds.RasterYSize

newXsize = int(newXsize)
newYsize = int(newYsize)
tlx, tly, newXsize, newYsize
```
```
(75969, 26781, 47196, 31937)
```

**Comment by gillins** [comment]
And what is the `outname`? And you have the KEA driver installed, right? Does KEA show up in the output of `gdal_translate --formats`?

**Comment by neilflood** [comment]
I don't know what is wrong. Hmmm.....

**Comment by juan-guerschman** [comment]
hold on...  not sure what I changed but it worked!

**Comment by juan-guerschman** [comment]
I'll close it, thanks both!

**Comment by gillins** [comment]
Great! Please let us know how you get on.

**Comment by gillins** [comment]
I should have also mentioned there are a couple of functions in https://www.pyshepseg.org/en/latest/pyshepseg_utils.html that might be useful. Either create a random colour table so you can see the different segments. Or create a colour table from some existing columns.
