### ISSUE TITLE
Dead links in README.md

### ISSUE THREAD

**Issue by pairmand** [ubarsc/kealib#9]
There are a couple of links called **downloads** in README.md that point at https://bitbucket.org/chchrsc/kealib/downloads which is no longer valid.

Are compiled  ArcPro drivers available anywhere?

Cheers
David

**Comment by gillins** [comment]
Thanks David, I'll fix this up. You can get the ArcGIS and ArcPro drivers from the release page (https://github.com/ubarsc/kealib/releases) then click on "Assets" for the latest release.

**Comment by pairmand** [comment]
Hi Sam,

Thanks for the quick reply. I downloaded setup_kea_arcpro_20200404.exe but got an error when running it: Unsupported ArcPro Version 2.6.

Actually, I have version 2.6.1 on this computer at home, but it works on my machine at work which is running ArcPro Version 2.4.2. I guess that I can install an earlier version of ArcPro to get it working.

Cheers
David.

**Comment by gillins** [comment]
Links have been updated and new build of Arc drivers available with support for latest versions (and some older ones removed).
